### ISSUE TITLE
ic_action_search included in archive?

### ISSUE THREAD

**Issue by TheIcemanCometh** [deano2390/FlowTextView#20]
I'm trying to use v2.0.2 of the library, but I'm getting a resource conflict with the ic_action_search image, as I'm including that in my res directory.  Is this actually needed by the library, and if not, can it be removed?

/Users/robert/AndroidStudioProjects/<app>/app/build/intermediates/res/debug/drawable-hdpi-v4/ic_action_search.png: error: Duplicate file.

**Comment by deano2390** [comment]
Should be sorted in 2.0.3
