### ISSUE TITLE
Project build failed

### ISSUE THREAD

**Issue by evasyuk** [deano2390/FlowTextView#21]
After adding 
   compile 'uk.co.deanwild:flowtextview:2.0.2@aar'
to dependencies list build is failing with:

%project_dir%\%main_module_name%\build\intermediates\res\debug\drawable-hdpi-v4\ic_launcher.png: error: Duplicate file.
%project_dir%\%main_module_name%\build\intermediates\res\debug\drawable-hdpi\ic_launcher.png: Original is here. The version qualifier may be implied.
Error:Execution failed for task ':actionsContentViewExample:processDebugResources'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command 'D:\dev\asdk\build-tools\22.0.1\aapt.exe'' finished with non-zero exit value 1

Any ideas how this could be solved?

**Comment by cwilkinson1998** [comment]
Simply removing the un-needed ic_launcher files from this library would fix the problem.

**Comment by deano2390** [comment]
Should be sorted in 2.0.3
